#!/bin/csh -f 

# 8 processors, unfluxed

echo "ages_specfit,  firstpass=0,  lastpass=5, /unfluxed" | idl > & specfit.log.01 &
echo "ages_specfit,  firstpass=6, lastpass=11, /unfluxed" | idl > & specfit.log.02 &
echo "ages_specfit, firstpass=12, lastpass=17, /unfluxed" | idl > & specfit.log.03 &
echo "ages_specfit, firstpass=18, lastpass=23, /unfluxed" | idl > & specfit.log.04 &
echo "ages_specfit, firstpass=24, lastpass=29, /unfluxed" | idl > & specfit.log.05 &
echo "ages_specfit, firstpass=30, lastpass=35, /unfluxed" | idl > & specfit.log.06 &
echo "ages_specfit, firstpass=36, lastpass=41, /unfluxed" | idl > & specfit.log.07 &
echo "ages_specfit, firstpass=42, lastpass=48, /unfluxed" | idl > & specfit.log.08 &
