#!/bin/csh -f 

# 8 processors, no tweak, part 2

echo "ages_specfit, firstpass=49, lastpass=54, /notweak" | idl > & specfit.log.09 &
echo "ages_specfit, firstpass=55, lastpass=60, /notweak" | idl > & specfit.log.10 &
echo "ages_specfit, firstpass=61, lastpass=66, /notweak" | idl > & specfit.log.11 &
echo "ages_specfit, firstpass=67, lastpass=72, /notweak" | idl > & specfit.log.12 &
echo "ages_specfit, firstpass=73, lastpass=78, /notweak" | idl > & specfit.log.13 &
echo "ages_specfit, firstpass=79, lastpass=84, /notweak" | idl > & specfit.log.14 &
echo "ages_specfit, firstpass=85, lastpass=90, /notweak" | idl > & specfit.log.15 &
echo "ages_specfit, firstpass=91, lastpass=100, /notweak" | idl > & specfit.log.16 &
