#!/bin/csh -f 

# np is the number of processors

# np = 6 & nmask = 400 & n1 = nmask/np & n2 = ceil(nmask/float(np))
# niceprint, lindgen(np)*n2, lindgen(np)*n2+n1

echo "deep2_specfit_dr4,   firstmask=0,  lastmask=66" | /usr/bin/nohup idl > & ~/deep2/specfit_dr4/specfit.log.01 &
echo "deep2_specfit_dr4,  firstmask=67, lastmask=133" | /usr/bin/nohup idl > & ~/deep2/specfit_dr4/specfit.log.02 &
echo "deep2_specfit_dr4, firstmask=134, lastmask=200" | /usr/bin/nohup idl > & ~/deep2/specfit_dr4/specfit.log.03 &

echo "deep2_specfit_dr4, firstmask=201, lastmask=267" | /usr/bin/nohup idl > & ~/deep2/specfit_dr4/specfit.log.04 &
echo "deep2_specfit_dr4, firstmask=268, lastmask=334" | /usr/bin/nohup idl > & ~/deep2/specfit_dr4/specfit.log.05 &
echo "deep2_specfit_dr4, firstmask=335, lastmask=400" | /usr/bin/nohup idl > & ~/deep2/specfit_dr4/specfit.log.06 &

